## Importing the necessary library

In [1]:
import numpy as np
import pandas as pd


## Importing the data for train and test set

In [2]:
train_df = pd.read_csv('/Users/neeraanand/mnist_train_small.csv')
test_df  = pd.read_csv('/Users/neeraanand/mnist_test.csv')

In [3]:
train_df.head()

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
test_df.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0  0.0  0.0  0.0  ...    0.0    0.0    0.0   
1  1  0    0    0    0    0    0  0.0  0.0  0.0  ...    0.0    0.0    0.0   
2  0  0    0    0    0    0    0  0.0  0.0  0.0  ...    0.0    0.0    0.0   
3  4  0    0    0    0    0    0  0.0  0.0  0.0  ...    0.0    0.0    0.0   
4  1  0    0    0    0    0    0  0.0  0.0  0.0  ...    0.0    0.0    0.0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 785 columns]

## Extracting the features from the train and test set

In [5]:
x_train = train_df.drop(['6'], axis=1).values

In [6]:
print(x_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
print(x_train.shape)

(19999, 784)


In [8]:
x_test = test_df.drop(columns = '7', index=1942).values

In [9]:
print(x_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Extracting the labels

In [10]:
y_train = train_df['6'].values

In [11]:
print(y_train)

[5 7 9 ... 2 9 5]


In [12]:
y_test = test_df['7'].drop(1942).values

In [13]:
print(y_test)

[2 1 0 ... 5 7 8]


In [14]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(len(np.unique(y_train)))

10


In [16]:
np.unique(y_test)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Normalisisng the train and test features

In [17]:
x_train = x_train/255
x_test = x_test/255

## One hot encoding

In [18]:
y_train_new = np.zeros([x_train.shape[0], len(np.unique(y_train))])

In [19]:
print(y_train_new.shape)

(19999, 10)


In [20]:
for i in range(len(np.unique(y_train))):
    for j in range(len(y_train_new)):
        if y_train[j]==np.unique(y_train)[i]:
            y_train_new[j, i]=1
        else:
            y_train_new[j, i] =0
print(y_train_new)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
y_test_new = np.zeros([x_test.shape[0], len(np.unique(y_test))])


In [22]:
for i in range(len(np.unique(y_test))):
    
    for j in range(len(y_test_new)):
        
        if y_test[j]==np.unique(y_test)[i]:
            
            y_test_new[j, i]=1
            
        else:
            
            y_test_new[j, i] = 0
            
print(y_test_new)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


## Defining the neural networks

In [23]:
def initialise_params(no_layer):
    parameters = {}
    n = len(no_layer)
    for i in range(1, n):
        parameters['W' + str(i)] = np.random.randn(no_layer[i],no_layer[i-1]) * 0.01
        parameters['b' + str(i)] = np.zeros((no_layer[i], 1))
    return parameters

In [24]:
def sigmoid(z):
    # sigmoid is also an activation function
    return (1/(1+np.exp(-z)))

In [25]:
def sigmoid_gradient(z):
    s = sigmoid(z)
    return s*(1-s)

In [26]:
def activation_forward(A_prev, W, b):
    
    #Z, A_prev, W, b = linear_forward(A_prev, W, b)
    Z = np.dot(W,A_prev)+b
    
    A= sigmoid(Z)
   
    
    return A , A_prev, W, b, Z


In [27]:
def forward_prop(X, parameters):
    temp1 = []
    A = X.T
    n = len(no_layer)  # number of layers in the neural network
    for l in range(1,n):
        A_prev = A
        A , A_prev, W, b, Z= activation_forward(A_prev, parameters['W' + str(l)], parameters['b' + str(l)])
        temp = A_prev, W, b, Z
        temp1.append(temp)
   
    return A, temp1

In [28]:
def computeCost(x, y):
    # cost function
    alpha = np.multiply(np.log(x), y.T) + np.multiply( np.log(1 - x),(1 - y.T))
    return - np.sum(alpha) / len(x_train)


In [29]:
def linear_backward(dZ, A_prev, W, b):
    
    m = A_prev.shape[1]

    dW = np.dot(dZ,A_prev.T)/m
    db = np.sum(dZ,axis=1)/m
    dA_prev = np.dot(W.T,dZ)


    return dA_prev, dW, db


In [30]:
def activation_backward(dA, temp):
    A_prev, W, b, Z = temp
   
    dZ = dA*sigmoid_gradient(Z)
    dA_prev, dW, db = linear_backward(dZ, A_prev, W, b)



    return dA_prev, dW, db 

In [45]:
def backward_prop(An, Y, temp1):
    grads = {}
    n = len(temp1) # the number of layers
    m = An.shape[1]
    Y = Y.reshape(An.shape)
    dAn = - (np.divide(Y, An) - np.divide(1 - Y, 1 - An))
    current_temp = temp1[n-1]
    grads["dA" + str(n)], grads["dW" + str(n)], grads["db" + str(n)] = activation_backward(dAn, current_temp)
    for l in reversed(range(n-1)):
        current_temp = temp1[l]
        dA_prev_temp, dW_temp, db_temp =activation_backward(grads["dA" + str(l+2)], current_temp)
        
        grads["dA" + str(l + 1)] = dA_prev_temp
        grads["dW" + str(l + 1)] = dW_temp
        grads["db" + str(l + 1)] = db_temp
        #print(grads)
    return grads
    
    

In [46]:
def update_parameters(parameters, grads, learning_rate):
    n = len(no_layer)  
    
    for l in range(1, n):
        parameters["W" + str(l)] = parameters["W" + str(l)] - learning_rate * grads["dW" + str(l)]
        parameters["b" + str(l)] = parameters["b" + str(l)] -learning_rate * grads["db" + str(l)].reshape(10, 1)
    #print(parameters)
    return parameters

In [47]:
no_layer = [784,10, 10, 10] 
def n_layer_model(X, Y, no_layer, learning_rate , iterations):
    parameters = initialise_params(no_layer)
    for i in range(0, iterations):
        An, temp1 = forward_prop(X, parameters)
        grads = backward_prop(An, Y, temp1)
        parameters = update_parameters(parameters, grads, learning_rate)
    return parameters


In [48]:
parameters = n_layer_model(x_train, y_train_new, no_layer, learning_rate = 0.0008, iterations = 2800)
#print(parameters)


In [49]:
A, temp = forward_prop(x_test, parameters)

In [50]:
y_pred = np.argmax(A, 0)

In [55]:
from sklearn.metrics import accuracy_score
print("Accuracy", accuracy_score(y_pred, y_test)*100)

Accuracy 87.5
